apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stream-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.loadBalancerIP}}
    networking.gke.io/managed-certificates: ssl-stream
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host:
      http:
        paths:
          - path:
            backend:
              serviceName: stream-service
              servicePort: 15002
