apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: stream-horizontal-pod-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream-deployment
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaler.metrics.cpu.targetAverageUtilization }}
